### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlexanderDykov**

### CODE REVIEW

**Comment by flyingfisch** [comment]
I'd like to give this a go, is there a description of the project somewhere? Are there any dependencies to get this up and running?

**Comment by ANDRON94** [comment]
Hi, flyingfisch. It was our test projects for a own use, so we didn't write any description.
For a local testing - just open in browser 'index.html' file.
For a remote usage - setup Node.js server(we use simple and fast 'express' Web-server). You can read a  lot of info about running Node.js applications at the Internet.
Thanks, Andron94

**Comment by flyingfisch** [comment]
Thanks, that's what I needed to know. :)

I'll start on the documentation tomorrow night.

**Comment by flyingfisch** [comment]
Oh woops, didn't realize this is a PR, not an issue... embarrassing :P 

Have fun with the hacktoberfest!

**Comment by ANDRON94** [comment]
You too =)

**Pull request merged**
